### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by Valid** [horatio-sans-serif/redis-node-client#28]
TypeError: Cannot read property 'length' of null
    at Client.handlePublishedMessage_ (/home/phazm/.node_libraries/redis-node-client/lib/redis-client.js:423:42)
    at Client.onReply_ (/home/phazm/.node_libraries/redis-node-client/lib/redis-client.js:390:14)
    at /home/phazm/.node_libraries/redis-node-client/lib/redis-client.js:136:34
    at ReplyParser.feed (/home/phazm/.node_libraries/redis-node-client/lib/redis-client.js:198:25)
    at Stream.<anonymous> (/home/phazm/.node_libraries/redis-node-client/lib/redis-client.js:337:28)
    at Stream.emit (events:25:26)
    at IOWatcher.callback (net:369:16)
    at node.js:204:9

Using the latest from HEAD for redis, node, and redis-node-client

I'm not actually doing anything with pubsub, so I think there's an errant call somewhere, when it's running the code when it doesn't need to.

**Comment by john-ka-peter** [comment]
That patch is worked for me

<a href="http://javascripttrainingcourses.com/JS/Node-JS-Training" title="Node.js Training in Chennai">Node.js Training in Chennai</a>
